### ISSUE TITLE
Material UI

### ISSUE THREAD

**Issue by trav3ll3r** [AndroidFromFrankfurt/linuxnews#9]
I anyone still looking after this repo? With authority to publish updates on PlayStore?

I'd like to finish off the work on Material Design UI but I'm not sure if project is still alive.

**Comment by Lesik** [comment]
Yes, I almost finished the Material Design rewrite, though I can't recall whether I pushed my changes or not (a glimpse into the commit history seems to suggest I didn't).

I'm glad you want to contribute! I would love any help I can receive, but please give me a few days to clean up some code and maybe find the changes I didn't push yet and put them online.

**Comment by Lesik** [comment]
Oh, and I hold the authority to publish to Play Store.

**Comment by trav3ll3r** [comment]
Sweet as, I was afraid this project got abandoned :)

I've made some changes that led to the new UI that looks like in attached screenshot below (colours are not final).
I also replaced List with RecylerView and used CardView for each RssItem.

I can make PR with this and you can cherry-pick what you like? Or let me know what needs re-work and I'll get on it :)

![material_design_sample](https://cloud.githubusercontent.com/assets/2419112/23093780/3cbe7db8-f640-11e6-91c3-f63f7924eb4a.png)

**Comment by Lesik** [comment]
Seems good. When I'm back home I'm going to merge your fork. Thanks a lot for your contribution.

Would you like to continue working on this app, or do you consider this a one-time contribution? I am asking because I'll gladly add you as a contributor to this repo if you are interested, so that you don't have to PR every change.

**Comment by trav3ll3r** [comment]
No worries, I really like the app and its simpicity. I'm happy to keep contributing, but this was the only thing I personally liked to see in the app.
I'd really like to see Notifications as well (as per #3,; see my comment).

Other than that perhaps we can draft out some feature road map?
